version: "3.7"
services:
  node:
    user: node
    image: node:15.8
    working_dir: /practical-vim
    ports:
      - ${PORT:-4010}:${PORT:-4010}
    environment:
      - PORT=${PORT:-4010}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ".:/practical-vim"
