version: "3.7"
services:
  node:
    user: node
    image: node:15.8
    working_dir: /practical-vim
    ports:
      - ${PORT:-4000}:${PORT:-4000}
    environment:
      - PORT=${PORT:-4000}
    volumes:
      - ".:/practical-vim"
    command: ls -lat
